name: build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  BUILD_TYPE: Release

jobs:  
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install cpplint
      - run: sudo apt install -y cppcheck clang-format
      
      - name: cpplint
        run: cpplint --exclude="src/client/graphics/imported/*" --recursive src
        
      - name: cppcheck
        run: cppcheck src
        
      - name: clang-format
        run: find src include tests -iname '*.h' -o -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format --dry-run -Werror
    
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3   

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
